### ISSUE TITLE
Volunteer clarity

### ISSUE THREAD

**Issue by xoneco** [kpchi/hackaguide#15]
> The lifeblood of any event: without their commitment and effort - even the best laid plans go to waste. So how do you aim to achieve that?

I'm being super pedantic regarding clarity in all these issues, but at the top of this section, would also just reiterate that this topic covers volunteer management **pre event**.

**Comment by kpchi** [comment]
### Proposed Fix

The *lifeblood* of any event: without their commitment and effort - even the best laid plans go to waste.  So how do you aim to achieve that?  This section will cover volunteer-related topics **Pre-Event**

**Comment by xoneco** [comment]
perfect
