### ISSUE TITLE
Link to gitbooks in github readme

### ISSUE THREAD

**Issue by xoneco** [kpchi/hackaguide#26]
At the top of the README:

https://kpchi.gitbooks.io/hackaguide/content/

**Comment by kpchi** [comment]
Not sure I follow.

**Comment by savage-engineer** [comment]
I believe the proposed change would mean adding a change like this to the README:

https://github.com/savage-engineer/hackaguide/commit/6b10fa11f88614b35c7aeaf09a6ddc269c1a3263

It was unclear from the README where I could view the guide online.

**Comment by xoneco** [comment]
Yup, exactly right @savage-engineer

**Comment by kpchi** [comment]
Ah, wasn't immediately clear - please go ahead and pull into the repo @savage-engineer.
